from src.config import (
    ASPECT_LABELS,
    NUM_ASPECTS,
    LLM_NAME,
    VIT_NAME,
    LLM_HIDDEN,
    VIT_HIDDEN,
    MAX_IMAGES,
    IMAGE_SIZE,
    MAX_TEXT_LEN,
    MAX_PATCH_TOKENS_PER_IMAGE,
    MAX_ROI_TOKENS_PER_IMAGE,
    LORA_R,
    LORA_ALPHA,
    LORA_TARGET_MODULES,
    LR_LORA,
    LR_OTHER,
    WEIGHT_DECAY,
    WARMUP_RATIO,
    BATCH_SIZE,
    GRADIENT_ACCUMULATION,
    MAX_EPOCHS,
    EARLY_STOPPING_PATIENCE,
    DATA_DIR,
    OUTPUT_DIR,
)

from src.vit_encoder import SigLIPEncoder
from src.projector_layer import MLPProjector, RoIProjector
from src.attention import (
    AspectQuery,
    TextRetriever,
    ImageRetriever,
    RoiRetriever,
    GatedFusion,
)
from src.aspect_model import MultimodalACSAModel, ClassificationHead
from src.data import (
    MultimodalSentimentDataset,
    collate_fn,
    build_dataloader,
)

__all__ = [
    # Config
    "ASPECT_LABELS",
    "NUM_ASPECTS",
    "LLM_NAME",
    "VIT_NAME",
    "LLM_HIDDEN",
    "VIT_HIDDEN",
    "MAX_IMAGES",
    "IMAGE_SIZE",
    "MAX_TEXT_LEN",
    "MAX_PATCH_TOKENS_PER_IMAGE",
    "MAX_ROI_TOKENS_PER_IMAGE",
    "LORA_R",
    "LORA_ALPHA",
    "LORA_TARGET_MODULES",
    "TEXT_RETRIEVER_HEADS",
    "IMG_RETRIEVER_HEADS",
    "ROI_RETRIEVER_HEADS",
    "LR_LORA",
    "LR_OTHER",
    "WEIGHT_DECAY",
    "WARMUP_RATIO",
    "BATCH_SIZE",
    "GRADIENT_ACCUMULATION",
    "MAX_EPOCHS",
    "EARLY_STOPPING_PATIENCE",
    "DATA_DIR",
    "OUTPUT_DIR",
    # Modules
    "SigLIPEncoder",
    "MLPProjector",
    "RoIProjector",
    "AspectQuery",
    "TextRetriever",
    "ImageRetriever",
    "RoiRetriever",
    "GatedFusion",
    "MultimodalACSAModel",
    "ClassificationHead",
    # Data
    "MultimodalSentimentDataset",
    "collate_fn",
    "build_dataloader",
]
