from dataclasses import dataclass


ASPECT_LABELS = ["Facilities", "Public_area", "Location", "Food", "Room", "Service"]
NUM_ASPECTS = len(ASPECT_LABELS)

LLM_NAME = "Qwen/Qwen3-4B-Instruct-2507"
VIT_NAME = "google/siglip2-so400m-patch16-256"

LLM_HIDDEN = 2560
VIT_HIDDEN = 1152

MAX_IMAGES = 7
IMAGE_SIZE = 256
MAX_TEXT_LEN = 256

MAX_PATCH_TOKENS_PER_IMAGE = 32
MAX_ROI_TOKENS_PER_IMAGE = 4

LORA_R = 64
LORA_ALPHA = 64
LORA_TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "o_proj"]

TEXT_RETRIEVER_HEADS = 8
IMG_RETRIEVER_HEADS = 4
ROI_RETRIEVER_HEADS = 4
FUSION_GATE_HIDDEN_MULT = 3  # hidden = d_h * 3

LR_LORA = 2e-5
LR_OTHER = 3e-5
WEIGHT_DECAY = 0.01
WARMUP_RATIO = 0.1

BATCH_SIZE = 8
GRADIENT_ACCUMULATION = 2
MAX_EPOCHS = 15
EARLY_STOPPING_PATIENCE = 4

DATA_DIR = "datasets"
OUTPUT_DIR = "outputs"
